In [1]:
# import libraries
import torch
import torch.nn as nn
import torch.nn.functional as F

import numpy as np
import matplotlib.pyplot as plt
from IPython import display
display.set_matplotlib_formats('svg')

/var/folders/nn/4_714bpd2qz7gm9d27_r3qw40000gn/T/ipykernel_21160/424189378.py:9: DeprecationWarning: `set_matplotlib_formats` is deprecated since IPython 7.23, directly use `matplotlib_inline.backend_inline.set_matplotlib_formats()`
  display.set_matplotlib_formats('svg')


In [2]:
widenet = nn.Sequential(
    nn.Linear(2, 4),
    nn.Linear(4, 3),
)

deepnet = nn.Sequential(
    nn.Linear(2, 2),
    nn.Linear(2, 2),
    nn.Linear(2, 3),
)

print(widenet)
print('')
print(deepnet)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)

Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)


In [3]:
for p in widenet.named_parameters():
    print(p)
    print('')

('0.weight', Parameter containing:
tensor([[ 0.0612,  0.6504],
        [ 0.6071, -0.3608],
        [-0.0217, -0.4795],
        [ 0.3482,  0.4702]], requires_grad=True))

('0.bias', Parameter containing:
tensor([ 0.0509,  0.1677, -0.3117, -0.3221], requires_grad=True))

('1.weight', Parameter containing:
tensor([[ 0.3295,  0.4920, -0.4567, -0.0373],
        [-0.3140, -0.3955, -0.2755, -0.3092],
        [-0.1786,  0.2255,  0.1338, -0.2377]], requires_grad=True))

('1.bias', Parameter containing:
tensor([ 0.0132, -0.0286,  0.2586], requires_grad=True))



In [11]:
for p in deepnet.named_parameters():
    print(p)
    print('')

('0.weight', Parameter containing:
tensor([[-0.3183, -0.5378],
        [-0.1843, -0.1841]], requires_grad=True))

('0.bias', Parameter containing:
tensor([0.0609, 0.3500], requires_grad=True))

('1.weight', Parameter containing:
tensor([[-0.4367, -0.5353],
        [-0.1591,  0.4856]], requires_grad=True))

('1.bias', Parameter containing:
tensor([0.5257, 0.2406], requires_grad=True))

('2.weight', Parameter containing:
tensor([[ 0.4732,  0.0300],
        [-0.5975, -0.3898],
        [-0.4772, -0.4237]], requires_grad=True))

('2.bias', Parameter containing:
tensor([ 0.5419, -0.0260,  0.3951], requires_grad=True))



In [12]:
numNodesInWide = 0
for paramName, paramVect in widenet.named_parameters():
    if 'bias' in paramName:
        numNodesInWide += len(paramVect)

numNodesInDeep = 0
for paramName, paramVect in deepnet.named_parameters():
    if 'bias' in paramName:
        numNodesInDeep += len(paramVect)

print('there are {} nodes in widenet'.format(numNodesInWide))
print('there are {} nodes in deepnet'.format(numNodesInDeep))


there are 7 nodes in widenet
there are 7 nodes in deepnet


In [14]:
for p in widenet.parameters():
    print(p)
    print('')
    print(p.numel())

Parameter containing:
tensor([[ 0.0612,  0.6504],
        [ 0.6071, -0.3608],
        [-0.0217, -0.4795],
        [ 0.3482,  0.4702]], requires_grad=True)

8
Parameter containing:
tensor([ 0.0509,  0.1677, -0.3117, -0.3221], requires_grad=True)

4
Parameter containing:
tensor([[ 0.3295,  0.4920, -0.4567, -0.0373],
        [-0.3140, -0.3955, -0.2755, -0.3092],
        [-0.1786,  0.2255,  0.1338, -0.2377]], requires_grad=True)

12
Parameter containing:
tensor([ 0.0132, -0.0286,  0.2586], requires_grad=True)

3


In [15]:
from torchsummary import summary
summary(widenet)

ModuleNotFoundError: No module named 'torchsummary'